markdown: rdiscount
auto: true
pygments: true
permalink: /:year/:month/:day/:title.html
name: Gyt
url: http://gyteng.com
email: igyteng@gmail.com
title: 轨迹
disqus: gyt
google_analytics: UA-23063930-2

